name: Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    # https://github.com/actions/virtual-environments#available-environments
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build -v --release
    - uses: actions/upload-artifact@v2
      with:
        name: tinyport-jp-304-macos-x86_64
        path: target/release/tinyport-jp-304
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Rust
        run: rustup component add rustfmt
      - run: cargo -v fmt -- --check
